# Generated by Django 5.2.9 on 2026-06-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volhelpapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='areas_of_interest',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='areas_of_interest',
            field=models.ManyToManyField(blank=True, to='volhelpapp.volunteeropportunity'),
        ),
    ]
